name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t sentiment-analysis-api .

    # Step 5: Run container (basic check)
    - name: Run Docker container
      run: |
        docker run -d -p 5000:80 --name sentiment sentiment-analysis-api
        sleep 5
        docker ps
name: CI Pipeline

on:
  push:
    branches: [ "main" ]   # run when you push to main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t sentiment-analysis-api .

      # Step 4: Run container (basic check)
      - name: Run Docker container
        run: |
          docker run -d -p 5000:80 --name sentiment sentiment-analysis-api
          sleep 5
          docker ps

